package io.github.hitoshura25.healthsyncapp.data.mapper.avroToRoom

import io.github.hitoshura25.healthsyncapp.avro.AvroSleepStageRecord
import io.github.hitoshura25.healthsyncapp.data.local.database.entity.SleepStageEntity

fun AvroSleepStageRecord.toSleepStageEntity(sessionHcUidParam: String): SleepStageEntity {
    return SleepStageEntity(
        // id is auto-generated by Room
        sessionHcUid = sessionHcUidParam, // Foreign key to the parent SleepSessionEntity
        startTimeEpochMillis = this.startTimeEpochMillis,
        endTimeEpochMillis = this.endTimeEpochMillis,
        stage = this.stage.name // Mapping AvroSleepStageType enum to its String name
    )
}