package io.github.hitoshura25.healthsyncapp.data.mapper

// Avro DTO imports
import io.github.hitoshura25.healthsyncapp.avro.AvroBloodGlucoseRecord
import io.github.hitoshura25.healthsyncapp.avro.AvroHeartRateRecord
import io.github.hitoshura25.healthsyncapp.avro.AvroSleepSessionRecord
import io.github.hitoshura25.healthsyncapp.avro.AvroSleepStageRecord // Added for the new mapper
import io.github.hitoshura25.healthsyncapp.avro.AvroStepsRecord
// Avro Enums
import io.github.hitoshura25.healthsyncapp.avro.AvroBloodGlucoseLevelUnit
import io.github.hitoshura25.healthsyncapp.avro.AvroMealType
import io.github.hitoshura25.healthsyncapp.avro.AvroRelationToMeal
import io.github.hitoshura25.healthsyncapp.avro.AvroSpecimenSource
import io.github.hitoshura25.healthsyncapp.avro.AvroSleepStageType

// Room Entity imports
import io.github.hitoshura25.healthsyncapp.data.local.database.entity.BloodGlucoseEntity
import io.github.hitoshura25.healthsyncapp.data.local.database.entity.HeartRateSampleEntity
import io.github.hitoshura25.healthsyncapp.data.local.database.entity.SleepSessionEntity
import io.github.hitoshura25.healthsyncapp.data.local.database.entity.SleepStageEntity // Now imported and used
import io.github.hitoshura25.healthsyncapp.data.local.database.entity.StepsRecordEntity

// --- Steps --- 
fun AvroStepsRecord.toStepsRecordEntity(): StepsRecordEntity {
    return StepsRecordEntity(
        // id is auto-generated by Room
        hcUid = this.hcUid,
        count = this.count,
        startTimeEpochMillis = this.startTimeEpochMillis,
        endTimeEpochMillis = this.endTimeEpochMillis,
        zoneOffsetId = this.startZoneOffsetId,
        appRecordFetchTimeEpochMillis = this.appRecordFetchTimeEpochMillis,
        isSynced = false
    )
}

// --- Heart Rate --- 
fun AvroHeartRateRecord.toHeartRateSampleEntities(): List<HeartRateSampleEntity> {
    val parentSessionRecordUid = this.hcUid
    val recordFetchedAtTime = this.appRecordFetchTimeEpochMillis
    val sessionStartZoneOffsetId = this.startZoneOffsetId

    return this.samples.map { avroSample ->
        HeartRateSampleEntity(
            // id is auto-generated by Room
            hcRecordUid = parentSessionRecordUid,
            sampleTimeEpochMillis = avroSample.timeEpochMillis,
            beatsPerMinute = avroSample.beatsPerMinute,
            zoneOffsetId = sessionStartZoneOffsetId,
            appRecordFetchTimeEpochMillis = recordFetchedAtTime,
            isSynced = false
        )
    }
}

// --- Sleep Stage (New Mapper) ---
fun AvroSleepStageRecord.toSleepStageEntity(sessionHcUidParam: String): SleepStageEntity {
    return SleepStageEntity(
        // id is auto-generated by Room
        sessionHcUid = sessionHcUidParam, // Foreign key to the parent SleepSessionEntity
        startTimeEpochMillis = this.startTimeEpochMillis,
        endTimeEpochMillis = this.endTimeEpochMillis,
        stage = this.stage.name // Mapping AvroSleepStageType enum to its String name
    )
}

// --- Sleep Session --- 
fun AvroSleepSessionRecord.toSleepSessionEntity(): SleepSessionEntity {
    // Note: Mapping of stages is handled separately. 
    // The service will map AvroSleepStageRecord list to SleepStageEntity list using the dedicated mapper.
    return SleepSessionEntity(
        // id is auto-generated by Room
        hcUid = this.hcUid,
        title = this.title,
        notes = this.notes,
        startTimeEpochMillis = this.startTimeEpochMillis,
        startZoneOffsetId = this.startZoneOffsetId,
        endTimeEpochMillis = this.endTimeEpochMillis,
        endZoneOffsetId = this.endZoneOffsetId,
        durationMillis = this.durationMillis,
        appRecordFetchTimeEpochMillis = this.appRecordFetchTimeEpochMillis,
        isSynced = false
    )
}

// --- Blood Glucose --- 

private fun mapSpecimenSourceToInt(avroSpecimenSource: AvroSpecimenSource): Int {
    return when (avroSpecimenSource) {
        AvroSpecimenSource.INTERSTITIAL_FLUID -> 1
        AvroSpecimenSource.CAPILLARY_BLOOD -> 2
        AvroSpecimenSource.PLASMA -> 3
        AvroSpecimenSource.SERUM -> 4
        AvroSpecimenSource.TEARS -> 5
        AvroSpecimenSource.WHOLE_BLOOD -> 6
        AvroSpecimenSource.UNKNOWN -> 0
    }
}

private fun mapMealTypeToInt(avroMealType: AvroMealType): Int {
    return when (avroMealType) {
        AvroMealType.BREAKFAST -> 1
        AvroMealType.LUNCH -> 2
        AvroMealType.DINNER -> 3
        AvroMealType.SNACK -> 4
        AvroMealType.UNKNOWN -> 0
    }
}

private fun mapRelationToMealToInt(avroRelationToMeal: AvroRelationToMeal): Int {
    return when (avroRelationToMeal) {
        AvroRelationToMeal.GENERAL -> 1
        AvroRelationToMeal.FASTING -> 2
        AvroRelationToMeal.BEFORE_MEAL -> 3
        AvroRelationToMeal.AFTER_MEAL -> 4
        AvroRelationToMeal.UNKNOWN -> 0
    }
}

fun AvroBloodGlucoseRecord.toBloodGlucoseEntity(): BloodGlucoseEntity {
    if (this.levelUnit == AvroBloodGlucoseLevelUnit.MILLIMOLES_PER_LITER) {
        // Log.w("BloodGlucoseMapper", "Received mmol/L, but entity expects mg/dL. Conversion needed.")
    }
    return BloodGlucoseEntity(
        // id is auto-generated by Room
        hcUid = this.hcUid,
        timeEpochMillis = this.timeEpochMillis,
        zoneOffsetId = this.zoneOffsetId,
        levelMgdL = this.levelValue, // Assumed to be in mg/dL
        specimenSource = mapSpecimenSourceToInt(this.specimenSource),
        mealType = mapMealTypeToInt(this.mealType),
        relationToMeal = mapRelationToMealToInt(this.relationToMeal),
        appRecordFetchTimeEpochMillis = this.appRecordFetchTimeEpochMillis,
        isSynced = false
    )
}
